apiVersion: v1
kind: Service
metadata:
  labels:
    app: warehouse-db
  name: warehouse-db
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: warehouse-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warehouse-db
  name: warehouse-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-db
  template:
    metadata:
      labels:
        app: warehouse-db
    spec:
      containers:
      - name: warehouse-db
        image: gcr.io/warehouse-software-322520/warehouse-db
        ports:
        - name: http
          containerPort: 5432
